application:
    build: docker/code
    volumes:
        - .:/var/www/symfony
        - ./logs/symfony:/var/www/symfony/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: my-homepage
        MYSQL_USER: user
        MYSQL_PASSWORD: root
php:
    build: docker/php7-fpm
    ports:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    build: docker/nginx
    ports:
        - 8888:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
       - 8889:80
   links:
       - db
   environment:
       - PMA_HOST=db
       - PMA_USER=root
       - PMA_PASSWORD=
       - PMA_ARBITRARY=1
