<?php

namespace AppBundle\Repository;

/**
 * GmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmailRepository extends \Doctrine\ORM\EntityRepository
{
}
