<?php

namespace AppBundle\Repository;

/**
 * TwitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterRepository extends \Doctrine\ORM\EntityRepository
{
}
